import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# code generated by chat gpt

# ============================================================
# CONFIGURATION
# ============================================================

DATA_DIR = Path("parquet_data")
PARQUET_FILES = sorted(DATA_DIR.glob("*/qtransform_features.parquet"))
OUTPUT_PARQUET = "tsne_results.parquet"
OUTPUT_PLOT = "tsne_clusters.png"

PERPLEXITY = 20
RANDOM_STATE = 42

PCA_COMPONENTS = 20


# ============================================================
# LOAD PARQUET FILES
# ============================================================

print("=" * 70)
print("LOADING PARQUET FILES")
print("=" * 70)

if len(PARQUET_FILES) == 0:
    raise FileNotFoundError(
        f"No parquet files found inside: {DATA_DIR}"
    )

print(f"Found {len(PARQUET_FILES)} parquet files.")

dataframes = []

for file in PARQUET_FILES:

    print(f"Loading: {file}")

    df = pd.read_parquet(file)

    # Keep the origin of each event
    df["source_file"] = file.name
    df["source_path"] = str(file)

    dataframes.append(df)


# ============================================================
# CONCATENATE DATASETS
# ============================================================

df_all = pd.concat(
    dataframes,
    ignore_index=True
)

print()
print("=" * 70)
print("COMBINED DATASET")
print("=" * 70)

print(f"Number of events: {len(df_all)}")
print(f"Number of columns: {len(df_all.columns)}")


# ============================================================
# SELECT FEATURES
# ============================================================

feature_columns = [
    col
    for col in df_all.columns
    if col.startswith("feature_")
]

if len(feature_columns) == 0:
    raise ValueError("No feature_* columns found.")

print(f"Number of features: {len(feature_columns)}")


X = df_all[feature_columns].to_numpy(dtype=np.float64)


# ============================================================
# CHECK DATA
# ============================================================

print()
print("Feature matrix:")
print(f"X.shape = {X.shape}")

print(f"NaN values: {np.isnan(X).sum()}")
print(f"Inf values: {np.isinf(X).sum()}")


# Replace invalid values if necessary

X = np.nan_to_num(X,nan=0.0,posinf=0.0,neginf=0.0)


# ============================================================
# STANDARDIZATION
# ============================================================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(f"Scaled matrix: {X_scaled.shape}")


# ============================================================
# PCA
# ============================================================

print()
print("=" * 70)
print("PCA")
print("=" * 70)

n_components = min(PCA_COMPONENTS,X_scaled.shape[0] - 1,X_scaled.shape[1])

pca = PCA(n_components=n_components,random_state=RANDOM_STATE)


X_pca = pca.fit_transform(X_scaled)
explained_variance = np.sum(pca.explained_variance_ratio_)

print(f"PCA components: {n_components}")
print(f"Explained variance: {explained_variance:.4f}")


# ============================================================
# t-SNE
# ============================================================

print()
print("=" * 70)
print("t-SNE")
print("=" * 70)

tsne = TSNE(n_components=2,perplexity=PERPLEXITY,init="pca",learning_rate="auto",random_state=RANDOM_STATE,)
X_tsne = tsne.fit_transform(X_pca)

print(f"t-SNE result: {X_tsne.shape}")


# ============================================================
# SAVE RESULTS
# ============================================================

df_result = pd.DataFrame({"trigger_time": df_all["trigger_time"].astype(str),"source_file": df_all["source_file"],"tsne_x": X_tsne[:, 0],"tsne_y": X_tsne[:, 1],})
df_result.to_parquet(OUTPUT_PARQUET,index=False)

print()
print(f"Saved: {OUTPUT_PARQUET}")


# ============================================================
# PLOT
# ============================================================

plt.figure(figsize=(12, 10))
plt.scatter(X_tsne[:, 0],X_tsne[:, 1],s=5,alpha=0.5)
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")

plt.title("t-SNE projection of Q-transform results")
plt.tight_layout()
plt.savefig(OUTPUT_PLOT,dpi=300)
#plt.show()